### ISSUE TITLE
Shiny Proxy Demo: Debugging "Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed" error

### ISSUE THREAD

**Issue by David-Degnan** [ucg8j/blog#5]
Hello! 

Thank you for this informative and helpful demo! When trying it on macOS 10.14.6, I ran into issues launching the 01 and 06 shiny proxy apps (the classic 500 error) after launching the jar file. After digging, I found the solution to be using the application-demo.yml file in shinyproxy/src/main/resources/application-demo.yml and running `socat TCP-LISTEN:2375,range=127.0.0.1/32,reuseaddr,fork UNIX-CLIENT:/var/run/docker.sock` in another terminal window. I think this is helpful information to include in your demo. More information can be found here: https://stackoverflow.com/questions/64216274/docker-desktop-for-mac-bind-to-tcp-port. I understand this configuration is not secure, but if you're just trying to learn how to run shiny proxy locally with minikube/docker desktop on mac, this is helpful to know. 

Feel free to add if you think it's worth it. Regardless, I hope posting this issue will help anyone else out there like me.

**Comment by ucg8j** [comment]
Thanks David - if people have the same issue, this should help them :+1:
